var d = document.getElementById("ready");
var dtx = d.getContext("2d");
var c = document.getElementById("game");
var ctx = c.getContext("2d"),
  speed = 0.5,
  box = 0,
  next = 0,
  next1 = 0,
  next2 = 0,
  size = 40,
  gr = "grey",
  aq = "aqua",
  y = "yellow",
  bl = "blue",
  r = "red",
  v = "violet",
  g = "green",
  o = "orange",
  color = [
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [r, r, r, r, r, r, r, r, r, r],
  ];

var bx = 3,
  by = -2,
  bw = 0.0,
  bh = 0.0,
  dem = 0.0,
  time = 0.0,
  speed = 0.0,
  tt = 0.0,
  day = false,
  a = 0,
  b = 0,
  c = 0,
  d = 0,
  e = 0,
  a_box_up = 0,
  b_box_up = 0,
  c_box_up = 0,
  d_box_up = 0,
  e_box_up = 0,
  demday = 0,
  left = false,
  right = false,
  xoay = 0,
  up,
  box_up = 0;
