var d = document.getElementById("ready");
var dtx = d.getContext("2d");
var c = document.getElementById("game");
var ctx = c.getContext("2d"),
  speed = 0.5,
  box = 0,
  next = 0,
  next1 = 0,
  next2 = 0,
  size = 40,
  xday = [],
  gr = "grey",
  aq = "aqua",
  y = "yellow",
  bl = "blue",
  r = "red",
  v = "violet",
  g = "green",
  o = "orange",
  color = [
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [gr, gr, gr, gr, gr, gr, gr, gr, gr, gr],
    [r, r, r, r, r, r, r, r, r, r],
  ];
for (let i = 0; i < 10; i++) {
  xday[i] = 20;
}
var bx = 3,
  by = -1,
  bw = 0,
  bh = 0,
  dem = 0,
  lastby = 0,
  a = 0,
  b = 0,
  c = 0,
  d = 0,
  e = 0;
